name: Docker

on:
  push:
    branches:
      - master

jobs:
    docker:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout
        - uses: actions/checkout@v2
        
        - name: Docker Build & Push to Docker Hub
          uses: opspresso/action-docker@master
          with:
            args: --docker
          env:
            USERNAME: ${{ secrets.DOCKER_USERNAME }}
            PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKERFILE: "Dockerfile"
            IMAGE_NAME: "mingxiaojing/linux-sqlserver"
            LATEST: "true"

